version: '3.7'

services:
  web:
    container_name: web-prod
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn music_festival.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db


  db:
    container_name: db-prod
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db


  nginx:
    container_name: nginx-prod
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume:
