# Generated by Django 3.0.6 on 2020-05-08 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Название')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[('1', 'Первый'), ('2', 'Второй')], null=True, verbose_name='День')),
                ('time', models.CharField(choices=[('DY', 'День'), ('NT', 'Вечер'), ('LN', 'Поздний вечер')], max_length=2, null=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
            },
        ),
        migrations.CreateModel(
            name='SceneSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num_of_performers', models.PositiveSmallIntegerField(null=True, verbose_name='Максимальное число выступающих')),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_slot', to='application_for_participation.Scene')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_slot', to='application_for_participation.TimeSlot')),
            ],
            options={
                'verbose_name': 'Сценослот',
                'verbose_name_plural': 'Сценослоты',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Название')),
                ('text', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('presentation_format', models.CharField(choices=[('SL', 'Сольное выступление'), ('GP', 'Группа')], max_length=2, null=True, verbose_name='Формат выступления')),
                ('comment', models.CharField(max_length=300, null=True, verbose_name='Коментарий')),
                ('desired_scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='application_for_participation.Scene')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
