# Generated by Django 3.0.6 on 2020-05-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_for_participation', '0002_auto_20200508_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='desired_timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='application_for_participation.TimeSlot'),
        ),
    ]
