# Generated by Django 3.0.6 on 2020-05-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_for_participation', '0003_application_desired_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='desired_timeslot',
            new_name='desired_time_slot',
        ),
    ]
