# Generated by Django 3.0.6 on 2020-05-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_for_participation', '0005_application_applications_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='desired_scene',
        ),
        migrations.RemoveField(
            model_name='application',
            name='desired_time_slot',
        ),
        migrations.AddField(
            model_name='application',
            name='desired_scene_and_time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='application_for_participation.SceneSlot'),
        ),
    ]
