# Generated by Django 3.0.6 on 2020-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_for_participation', '0006_auto_20200510_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rating',
            field=models.SmallIntegerField(null=True, verbose_name='Рейтинг'),
        ),
    ]
