# Generated by Django 3.0.6 on 2020-05-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_for_participation', '0007_application_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rating',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
