# Generated by Django 3.0.6 on 2020-05-11 19:12

import application_for_participation.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_for_participation', '0008_auto_20200510_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='voted_sensors',
            field=application_for_participation.models.ListField(null=True, token=','),
        ),
    ]
