# Generated by Django 3.0.6 on 2020-05-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='musician_or_sensor',
            field=models.CharField(choices=[('MC', 'Музыкант'), ('SS', 'Цензор')], max_length=2, null=True, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя/Название группы'),
        ),
    ]
