# Generated by Django 3.0.6 on 2020-05-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_creation', '0002_auto_20200507_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(default=False, null=True, verbose_name='Верифицирован (поле Только для цензоров)'),
        ),
    ]
