# Generated by Django 3.0.6 on 2020-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=300, null=True, verbose_name='Название')),
                ('where', models.CharField(max_length=300, null=True, verbose_name='Где')),
                ('when', models.DateField(null=True, verbose_name='Когда')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Служебная инвормация',
                'verbose_name_plural': 'Служебная инвормация',
            },
        ),
    ]
