# Generated by Django 3.0.6 on 2020-05-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scene',
            new_name='Information',
        ),
    ]
